CC = gcc
NAME = fdf
CFLAGS = -Wall -Werror -Wextra
SRC = fdf.c fdf.h
OBJ = $(SRC:.c=.o)
LIBX = -lm -I/usr/X11/include -I/libs/fdf/includes -L/usr/X11/lib -lX11 -lXext -lmlx -L libs/ -lft
#LIBXL = -lm -L libs/ -lft -L/usr/lib/X11 -lmlx -lXext -lX11


all : $(NAME)


$(NAME) : fdf.o libs
	@echo "Creating MAC executable $(NAME) ..."
	@gcc $(CFLAGS) -I/libs/fdf/includes -c $(SRC)
#	@gcc -o $(OBJ) $(LIBX)

libs:
	@make -C libs fclean
	@make -C libs

clean :
	@echo "Removing object files ..."
	@rm -f $(OBJ)

fclean : clean
	@echo "Removing $(NAME) ..."
	@rm -f $(NAME)

re : fclean all
